### ISSUE TITLE
Update to astro 3.x

### ISSUE THREAD

**Issue by alec-c4** [satnaing/astro-paper#111]
Hey!
Are there any plans to update the theme to support astro 3.x?

**Comment by satnaing** [comment]
Yes
I'm currently working on it.

**Comment by susanta96** [comment]
Great !! I am using this as well. It would be better to use, v3. However, I am upgrading it but when I tried to use ViewTransition API, which is the new one in v3. It's breaking the toggle theme functionality between pages. 

Please try to resolve this, if possible. I am also trying to resolve this, Viewtranstions is also calling other pages beforehand as well.

**Comment by hanskalisvaart** [comment]
Can someone smarter than me tell me why Astro 3.x broke the header?

**Comment by tanishqmanuja** [comment]
@hanskalisvaart, can you try if `scopedStyleStrategy: "where"` in astro config fixes it ?

**Comment by nimrra** [comment]
i also want to use ViewTransition API,

**Comment by hanskalisvaart** [comment]
> @hanskalisvaart, can you try if `scopedStyleStrategy: "where"` in astro config fixes it ? EDIT: also have to add transition:persist to header
> 
> ```
> <header transition:persist>
>   ...
> </header>
> ```

Putting Putting scopedStyleStrategy: "where" in the astro.config.mjs file at the location:
 export default defineConfig({
  scopedStyleStrategy: 'where',
fixed the header!

**Comment by satnaing** [comment]
Hello everyone!

I just made a PR for Astro v3 and ViewTransitions API; plus a few minor updates. You can give suggestions and try experimenting with it on [version-3 branch](https://github.com/satnaing/astro-paper/tree/feature/version-3) or [live URL](https://astro-paper.pages.dev/)
You can also give feedback on my implementation details, trade-offs I've made, or anything.

Thanks

**Comment by Jordain** [comment]
Hey Satnaing, if you are in dark mode and click on any of the header links it flashes white before changing back to black.

**Comment by satnaing** [comment]
Hello @Jordain 
Does that problem still exist in [AstroPaper v3](https://astro-paper.pages.dev/)?

On which browser does it happen?

**Comment by Jordain** [comment]
@satnaing Yep, Firefox

**Comment by satnaing** [comment]
> Hey Satnaing, if you are in dark mode and click on any of the header links it flashes white before changing back to black.

Previously, commit fdabb82 introduced a transition effect for the background color when toggling between light and dark modes. This effect caused a white flash when clicking on header links in dark mode, especially in Firefox. 
It appears that this theme switch transition effect was somehow triggered whenever navigating. To fix this, for now, I just removed the transition code in the body.

Thanks for pointing this out @Jordain
